name: Demos
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os:
          - ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Setup Node 18
        uses: actions/setup-node@v2
        with:
          node-version: "18"
      - uses: pnpm/action-setup@v2
        name: Install pnpm
        with:
          version: 8
          run_install: false
      - name: Install
        run: pnpm install
      - name: Build
        run: pnpm build
      - name: Prepare
        run: |
            mkdir _deploy
            mkdir _deploy/webpack-app
            cp -R demos/webpack-app/public/* _deploy/webpack-app
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: _deploy
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v1
